class SituacaoRelacionamento

  APROVADO = "APROVADO"
  REPROVADO = "REPROVADO"
  AGUARDANDO_REPOSTA = "AGUARDANDO_RESPOSTA"

  SITUACOES_RELACIONAMENTOS = [APROVADO, REPROVADO, AGUARDANDO_REPOSTA]



end
